### ISSUE TITLE
Why the OR in `event.timestamp < self.last_updated || event.seq < self.last_sequence`?

### ISSUE THREAD

**Issue by umbertov** [ninja-quant/ninjabook#2]
Hi, I began using this crate lately after finding it a while ago. I stumbled upon the following lines in `Orderbook::process()`:
```rust
    pub fn process(&mut self, event: Event) {
        if event.timestamp < self.last_updated || event.seq < self.last_sequence {
            return;
        }
        ...
    }
```

Where I was expecting a AND `&&`, I found an OR `||`. 
In my mind, and in practice, you can get level 2 orderbook updates for multiple levels with the same timestamp, something like
```python
[ {level: 1, timestamp: 7, size: 0.1, price: 0.1}, {level: 2, timestamp: 7, size: 0.1, price: 0.11} ] 
```

In this case, I craft 2 `Event` structs, with a different `.seq` number, but since the timestamp is the same, the update is rejected.

I'm looking for a way to get around the issue, is there an intended use that i'm missing here?

**Comment by ninja-quant** [comment]
Thank you for pointing this out! I have just pushed the fix. Please feel free to test the library further and let me know if you find anything else.
